package hello;

import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.factory.GraphDatabaseFactory;

import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public App(){
        GraphDatabaseService graphDb = new GraphDatabaseFactory().newEmbeddedDatabase(new File("graph.db"));
        Runtime.getRuntime().addShutdownHook(new Thread( graphDb::shutdown ) );
    }


    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
